default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: app_capistrano_development

test:
  <<: *default
  database: app_capistrano_test

production:
  <<: *default
  database: <%= ENV['APP_CAPISTRANO_DATABASE_BD'] %>
  username: <%= ENV['APP_CAPISTRANO_DATABASE_USERNAME'] %>
  password: <%= ENV['APP_CAPISTRANO_DATABASE_PASSWORD'] %>
